include tokyonight.conf

font_family JetBrainsMono Nerd Font
font_size 12

window_padding_width 8
confirm_os_window_close 0
enable_audio_bell no
remember_window_size no
initial_window_width 78c
initial_window_height 23c
window_padding_widht 30
background_opacity 0.50
url_color #e8eaed

confirm_os_window_close 0
sync_to_monitor no
